2021-04-01 at 12:05:45 🔖   INFO     Found additional log level customization: 💪   SUCCESS                                                💻 log.py@init:75 ⏰ 0:00:01.741946
2021-04-01 at 12:05:45 🔖   INFO     Found additional log level customization: 👀   WARN                                                   💻 log.py@init:75 ⏰ 0:00:01.743949
2021-04-01 at 12:05:45 🔖   INFO     Found additional log level customization: 🔖   INFO                                                   💻 log.py@init:75 ⏰ 0:00:01.743949
2021-04-01 at 12:05:45 🔖   INFO     Found additional log level customization: ❌   ERROR                                                  💻 log.py@init:75 ⏰ 0:00:01.745946
2021-04-01 at 12:05:45 🔖   INFO     Found additional log level customization: 🎯   NOTICE                                                 💻 log.py@init:75 ⏰ 0:00:01.745946
2021-04-01 at 12:05:45 🔖   INFO     Found additional log level customization: 💩   SPAM                                                   💻 log.py@init:75 ⏰ 0:00:01.749006
2021-04-01 at 12:05:45 🔖   INFO     Found additional log level customization: 📝   VERBOSE                                                💻 log.py@init:75 ⏰ 0:00:01.749946
2021-04-01 at 12:05:45 🔖   INFO     Found additional log level customization: 💥   CRITICAL                                               💻 log.py@init:75 ⏰ 0:00:01.750948
2021-04-01 at 12:05:45 🎯   NOTICE   JWT authentication disabled                                                                          💻 __init__.py@api:37 ⏰ 0:00:01.750948
2021-04-01 at 12:05:45 🎯   NOTICE   HTTPS not set                                                                                        💻 __init__.py@api:43 ⏰ 0:00:01.751947
2021-04-01 at 12:05:45 🎯   NOTICE   Elastic APM disabled                                                                                 💻 __init__.py@api:49 ⏰ 0:00:01.752950
2021-04-01 at 12:05:45 🔖   INFO     Check connection to http://localhost:9000/polycube/v1                                                💻 polycube.py@__init__:25 ⏰ 0:00:01.992947
2021-04-01 at 12:05:45 ❌   ERROR    Connection with polycube at localhost:9000 not possible                                              💻 polycube.py@__init__:31 ⏰ 0:00:02.001778
Traceback (most recent call last):
  File "C:\db-p\work\projects\guard\gitlab_repositories\guard-lcp\lib\polycube.py", line 29, in __init__
    self.__manager(resp_req)
  File "C:\db-p\work\projects\guard\gitlab_repositories\guard-lcp\lib\polycube.py", line 135, in __manager
    resp_req.raise_for_status()
  File "C:\Users\aless\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:9000/polycube/v1
2021-04-01 at 12:05:45 💪   SUCCESS  /code endpoint configured                                                                            💻 __init__.py@routes:22 ⏰ 0:00:02.028973
2021-04-01 at 12:05:45 💪   SUCCESS  /code/{id} endpoint configured                                                                       💻 __init__.py@routes:22 ⏰ 0:00:02.047415
2021-04-01 at 12:05:45 💪   SUCCESS  /config endpoint configured                                                                          💻 __init__.py@routes:22 ⏰ 0:00:02.061291
2021-04-01 at 12:05:45 💪   SUCCESS  /status endpoint configured                                                                          💻 __init__.py@routes:22 ⏰ 0:00:02.069259
2021-04-01 at 12:05:45 💪   SUCCESS  Accept requests at 0.0.0.0:4567                                                                      💻 main.py@<module>:34 ⏰ 0:00:02.117258
